#! /usr/bin/env python

import os, glob, sys

def build(bld):
    bld.program(
        source = bld.path.ant_glob('*.c*'),
        target = 'dhcore-test' + bld.env.SUFFIX,
        includes = ['../../include'],
        install_path = '${PREFIX}/bin',
        use = ['dhcore'])

