#! /usr/bin/env python

import os
def build(bld):
    files = bld.path.ant_glob('*.c')

    bld.program(
        source = files,
        target = 'dhcore-test' + bld.env.SUFFIX,
        install_path = '${PREFIX}/bin',
        use = ['dhcore'])

